/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-22 05:46:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("\n");
      out.write("  <title>Ninestars Bootstrap Template - Index</title>\n");
      out.write("  <meta content=\"\" name=\"description\">\n");
      out.write("  <meta content=\"\" name=\"keywords\">\n");
      out.write("\n");
      out.write("  <!-- Favicons -->\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("  <!-- Google Fonts -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Vendor CSS Files -->\n");
      out.write("  <link href=\"assets/vendor/aos/aos.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"assets/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Template Main CSS File -->\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- =======================================================\n");
      out.write("  * Template Name: Ninestars - v4.8.0\n");
      out.write("  * Template URL: https://bootstrapmade.com/ninestars-free-bootstrap-3-theme-for-creative/\n");
      out.write("  * Author: BootstrapMade.com\n");
      out.write("  * License: https://bootstrapmade.com/license/\n");
      out.write("  ======================================================== -->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- ======= Header ======= -->\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\n");
      out.write("  <!-- End Header -->\n");
      out.write("\n");
      out.write("  <!-- ======= Hero Section ======= -->\n");
      out.write("  <section id=\"hero\" class=\"d-flex align-items-center\">\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row gy-4\">\n");
      out.write("        <div class=\"col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center\">\n");
      out.write("          <h1>Service for the busy worker who wants to spend time with your fluffy friends</h1>\n");
      out.write("          <h2>털복숭이 친구들과 함께 하고싶은 바쁜 직장인을 위해</h2>\n");
      out.write("          <div>\n");
      out.write("            <a href=\"#about\" class=\"btn-get-started scrollto\">예약하러 가기</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 order-1 order-lg-2 hero-img\">\n");
      out.write("          <img src=\"assets/img/main_dogcat.png\" class=\"img-fluid animated\" alt=\"\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </section><!-- End Hero -->\n");
      out.write("\n");
      out.write("  <main id=\"main\">\n");
      out.write("\n");
      out.write("    <!-- ======= About Section ======= -->\n");
      out.write("    <section id=\"about\" class=\"about\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"row justify-content-between\">\n");
      out.write("          <div class=\"col-lg-5 d-flex align-items-center justify-content-center about-img\">\n");
      out.write("            <img src=\"assets/img/about-img.svg\" class=\"img-fluid\" alt=\"\" data-aos=\"zoom-in\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-6 pt-5 pt-lg-0\">\n");
      out.write("            <h3 data-aos=\"fade-up\">Voluptatem dignissimos provident quasi</h3>\n");
      out.write("            <p data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit\n");
      out.write("            </p>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-6\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("                <i class=\"bx bx-receipt\"></i>\n");
      out.write("                <h4>Corporis voluptates sit</h4>\n");
      out.write("                <p>Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip</p>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6\" data-aos=\"fade-up\" data-aos-delay=\"200\">\n");
      out.write("                <i class=\"bx bx-cube-alt\"></i>\n");
      out.write("                <h4>Ullamco laboris nisi</h4>\n");
      out.write("                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End About Section -->\n");
      out.write("\n");
      out.write("    <!-- ======= Services Section ======= -->\n");
      out.write("    <section id=\"services\" class=\"services section-bg\">\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">\n");
      out.write("          <h2>Services</h2>\n");
      out.write("          <p>Check out the great services we offer</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex align-items-stretch\" data-aos=\"zoom-in\" data-aos-delay=\"100\">\n");
      out.write("            <div class=\"icon-box\">\n");
      out.write("              <div class=\"icon\"><i class=\"bx bxl-dribbble\"></i></div>\n");
      out.write("              <h4 class=\"title\"><a href=\"\">Lorem Ipsum</a></h4>\n");
      out.write("              <p class=\"description\">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex align-items-stretch\" data-aos=\"zoom-in\" data-aos-delay=\"200\">\n");
      out.write("            <div class=\"icon-box\">\n");
      out.write("              <div class=\"icon\"><i class=\"bx bx-file\"></i></div>\n");
      out.write("              <h4 class=\"title\"><a href=\"\">Sed ut perspiciatis</a></h4>\n");
      out.write("              <p class=\"description\">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex align-items-stretch\" data-aos=\"zoom-in\" data-aos-delay=\"300\">\n");
      out.write("            <div class=\"icon-box\">\n");
      out.write("              <div class=\"icon\"><i class=\"bx bx-tachometer\"></i></div>\n");
      out.write("              <h4 class=\"title\"><a href=\"\">Magni Dolores</a></h4>\n");
      out.write("              <p class=\"description\">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-6 col-lg-3 d-flex align-items-stretch\" data-aos=\"zoom-in\" data-aos-delay=\"400\">\n");
      out.write("            <div class=\"icon-box\">\n");
      out.write("              <div class=\"icon\"><i class=\"bx bx-world\"></i></div>\n");
      out.write("              <h4 class=\"title\"><a href=\"\">Nemo Enim</a></h4>\n");
      out.write("              <p class=\"description\">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End Services Section -->\n");
      out.write("\n");
      out.write("    <!-- ======= Portfolio Section ======= -->\n");
      out.write("    <section id=\"portfolio\" class=\"portfolio\">\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">\n");
      out.write("          <h2>Portfolio</h2>\n");
      out.write("          <p>Check out our beautifull portfolio</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("          <div class=\"col-lg-12\">\n");
      out.write("            <ul id=\"portfolio-flters\">\n");
      out.write("              <li data-filter=\"*\" class=\"filter-active\">All</li>\n");
      out.write("              <li data-filter=\".filter-app\">App</li>\n");
      out.write("              <li data-filter=\".filter-card\">Card</li>\n");
      out.write("              <li data-filter=\".filter-web\">Web</li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row portfolio-container\" data-aos=\"fade-up\" data-aos-delay=\"200\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-1.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-1.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"App 1\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>App 1</h4>\n");
      out.write("                <p>App</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-web\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-2.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-2.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"Web 3\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>Web 3</h4>\n");
      out.write("                <p>Web</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-3.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-3.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"App 2\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>App 2</h4>\n");
      out.write("                <p>App</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-card\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-4.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-4.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"Card 2\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>Card 2</h4>\n");
      out.write("                <p>Card</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-web\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-5.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-5.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"Web 2\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>Web 2</h4>\n");
      out.write("                <p>Web</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-app\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-6.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-6.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"App 3\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>App 3</h4>\n");
      out.write("                <p>App</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-card\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-7.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-7.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"Card 1\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>Card 1</h4>\n");
      out.write("                <p>Card</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-card\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-8.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-8.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"Card 3\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>Card 3</h4>\n");
      out.write("                <p>Card</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 portfolio-item filter-web\">\n");
      out.write("            <div class=\"portfolio-wrap\">\n");
      out.write("              <img src=\"assets/img/portfolio/portfolio-9.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"portfolio-links\">\n");
      out.write("                <a href=\"assets/img/portfolio/portfolio-9.jpg\" data-gallery=\"portfolioGallery\" class=\"portfolio-lightbox\" title=\"Web 3\"><i class=\"bi bi-plus\"></i></a>\n");
      out.write("                <a href=\"portfolio-details.html\" title=\"More Details\"><i class=\"bi bi-link\"></i></a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"portfolio-info\">\n");
      out.write("                <h4>Web 3</h4>\n");
      out.write("                <p>Web</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End Portfolio Section -->\n");
      out.write("\n");
      out.write("    <!-- ======= F.A.Q Section ======= -->\n");
      out.write("    <section id=\"faq\" class=\"faq section-bg\">\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">\n");
      out.write("          <h2>F.A.Q</h2>\n");
      out.write("          <p>Frequently Asked Questions</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <ul class=\"faq-list\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <div data-bs-toggle=\"collapse\" class=\"collapsed question\" href=\"#faq1\">Non consectetur a erat nam at lectus urna duis? <i class=\"bi bi-chevron-down icon-show\"></i><i class=\"bi bi-chevron-up icon-close\"></i></div>\n");
      out.write("            <div id=\"faq1\" class=\"collapse\" data-bs-parent=\".faq-list\">\n");
      out.write("              <p>\n");
      out.write("                Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <div data-bs-toggle=\"collapse\" href=\"#faq2\" class=\"collapsed question\">Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque? <i class=\"bi bi-chevron-down icon-show\"></i><i class=\"bi bi-chevron-up icon-close\"></i></div>\n");
      out.write("            <div id=\"faq2\" class=\"collapse\" data-bs-parent=\".faq-list\">\n");
      out.write("              <p>\n");
      out.write("                Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <div data-bs-toggle=\"collapse\" href=\"#faq3\" class=\"collapsed question\">Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi? <i class=\"bi bi-chevron-down icon-show\"></i><i class=\"bi bi-chevron-up icon-close\"></i></div>\n");
      out.write("            <div id=\"faq3\" class=\"collapse\" data-bs-parent=\".faq-list\">\n");
      out.write("              <p>\n");
      out.write("                Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar elementum integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu tincidunt. Lectus urna duis convallis convallis tellus. Urna molestie at elementum eu facilisis sed odio morbi quis\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <div data-bs-toggle=\"collapse\" href=\"#faq4\" class=\"collapsed question\">Ac odio tempor orci dapibus. Aliquam eleifend mi in nulla? <i class=\"bi bi-chevron-down icon-show\"></i><i class=\"bi bi-chevron-up icon-close\"></i></div>\n");
      out.write("            <div id=\"faq4\" class=\"collapse\" data-bs-parent=\".faq-list\">\n");
      out.write("              <p>\n");
      out.write("                Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <div data-bs-toggle=\"collapse\" href=\"#faq5\" class=\"collapsed question\">Tempus quam pellentesque nec nam aliquam sem et tortor consequat? <i class=\"bi bi-chevron-down icon-show\"></i><i class=\"bi bi-chevron-up icon-close\"></i></div>\n");
      out.write("            <div id=\"faq5\" class=\"collapse\" data-bs-parent=\".faq-list\">\n");
      out.write("              <p>\n");
      out.write("                Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <div data-bs-toggle=\"collapse\" href=\"#faq6\" class=\"collapsed question\">Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor? <i class=\"bi bi-chevron-down icon-show\"></i><i class=\"bi bi-chevron-up icon-close\"></i></div>\n");
      out.write("            <div id=\"faq6\" class=\"collapse\" data-bs-parent=\".faq-list\">\n");
      out.write("              <p>\n");
      out.write("                Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nibh tellus molestie nunc non blandit massa enim nec.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End F.A.Q Section -->\n");
      out.write("\n");
      out.write("    <!-- ======= Team Section ======= -->\n");
      out.write("    <section id=\"team\" class=\"team\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\" data-aos=\"fade-up\">\n");
      out.write("          <h2>Team</h2>\n");
      out.write("          <p>Our team is always here to help</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-xl-3 col-lg-4 col-md-6\" data-aos=\"zoom-in\" data-aos-delay=\"100\">\n");
      out.write("            <div class=\"member\">\n");
      out.write("              <img src=\"assets/img/team/team-1.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"member-info\">\n");
      out.write("                <div class=\"member-info-content\">\n");
      out.write("                  <h4>Walter White</h4>\n");
      out.write("                  <span>Chief Executive Officer</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"social\">\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-twitter\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-facebook\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-instagram\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-linkedin\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-xl-3 col-lg-4 col-md-6\" data-aos=\"zoom-in\" data-aos-delay=\"200\">\n");
      out.write("            <div class=\"member\">\n");
      out.write("              <img src=\"assets/img/team/team-2.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"member-info\">\n");
      out.write("                <div class=\"member-info-content\">\n");
      out.write("                  <h4>Sarah Jhonson</h4>\n");
      out.write("                  <span>Product Manager</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"social\">\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-twitter\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-facebook\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-instagram\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-linkedin\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-xl-3 col-lg-4 col-md-6\" data-aos=\"zoom-in\" data-aos-delay=\"300\">\n");
      out.write("            <div class=\"member\">\n");
      out.write("              <img src=\"assets/img/team/team-3.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"member-info\">\n");
      out.write("                <div class=\"member-info-content\">\n");
      out.write("                  <h4>William Anderson</h4>\n");
      out.write("                  <span>CTO</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"social\">\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-twitter\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-facebook\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-instagram\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-linkedin\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-xl-3 col-lg-4 col-md-6\" data-aos=\"zoom-in\" data-aos-delay=\"400\">\n");
      out.write("            <div class=\"member\">\n");
      out.write("              <img src=\"assets/img/team/team-4.jpg\" class=\"img-fluid\" alt=\"\">\n");
      out.write("              <div class=\"member-info\">\n");
      out.write("                <div class=\"member-info-content\">\n");
      out.write("                  <h4>Amanda Jepson</h4>\n");
      out.write("                  <span>Accountant</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"social\">\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-twitter\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-facebook\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-instagram\"></i></a>\n");
      out.write("                  <a href=\"\"><i class=\"bi bi-linkedin\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End Team Section -->\n");
      out.write("\n");
      out.write("    <!-- ======= Clients Section ======= -->\n");
      out.write("    <section id=\"clients\" class=\"clients section-bg\">\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">\n");
      out.write("          <h2>Clients</h2>\n");
      out.write("          <p>They trusted us</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"clients-slider swiper\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("          <div class=\"swiper-wrapper align-items-center\">\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-1.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-2.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-3.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-4.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-5.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-6.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-7.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("            <div class=\"swiper-slide\"><img src=\"assets/img/clients/client-8.png\" class=\"img-fluid\" alt=\"\"></div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"swiper-pagination\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End Clients Section -->\n");
      out.write("\n");
      out.write("    <!-- ======= Contact Us Section ======= -->\n");
      out.write("    <section id=\"contact\" class=\"contact\">\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">\n");
      out.write("          <h2>Contact Us</h2>\n");
      out.write("          <p>Contact us the get started</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-5 d-flex align-items-stretch\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("            <div class=\"info\">\n");
      out.write("              <div class=\"address\">\n");
      out.write("                <i class=\"bi bi-geo-alt\"></i>\n");
      out.write("                <h4>Location:</h4>\n");
      out.write("                <p>A108 Adam Street, New York, NY 535022</p>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"email\">\n");
      out.write("                <i class=\"bi bi-envelope\"></i>\n");
      out.write("                <h4>Email:</h4>\n");
      out.write("                <p>info@example.com</p>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"phone\">\n");
      out.write("                <i class=\"bi bi-phone\"></i>\n");
      out.write("                <h4>Call:</h4>\n");
      out.write("                <p>+1 5589 55488 55s</p>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621\" frameborder=\"0\" style=\"border:0; width: 100%; height: 290px;\" allowfullscreen></iframe>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch\" data-aos=\"fade-up\" data-aos-delay=\"200\">\n");
      out.write("            <form action=\"forms/contact.php\" method=\"post\" role=\"form\" class=\"php-email-form\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"form-group col-md-6\">\n");
      out.write("                  <label for=\"name\">Your Name</label>\n");
      out.write("                  <input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group col-md-6 mt-3 mt-md-0\">\n");
      out.write("                  <label for=\"name\">Your Email</label>\n");
      out.write("                  <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"Your Email\" required>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"name\">Subject</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"subject\" id=\"subject\" placeholder=\"Subject\" required>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group mt-3\">\n");
      out.write("                <label for=\"name\">Message</label>\n");
      out.write("                <textarea class=\"form-control\" name=\"message\" rows=\"10\" required></textarea>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"my-3\">\n");
      out.write("                <div class=\"loading\">Loading</div>\n");
      out.write("                <div class=\"error-message\"></div>\n");
      out.write("                <div class=\"sent-message\">Your message has been sent. Thank you!</div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"text-center\"><button type=\"submit\">Send Message</button></div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- End Contact Us Section -->\n");
      out.write("\n");
      out.write("  </main><!-- End #main -->\n");
      out.write("\n");
      out.write("  <!-- ======= Footer ======= -->\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      out.write("\n");
      out.write("  <!-- End Footer -->\n");
      out.write("\n");
      out.write("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\n");
      out.write("\n");
      out.write("  <!-- Vendor JS Files -->\n");
      out.write("  <script src=\"assets/vendor/aos/aos.js\"></script>\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <script src=\"assets/vendor/glightbox/js/glightbox.min.js\"></script>\n");
      out.write("  <script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\n");
      out.write("  <script src=\"assets/vendor/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Template Main JS File -->\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
