/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-21 10:33:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>자유게시판</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\">\n");
      out.write("<link rel='stylesheet'\n");
      out.write("	href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900'>\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/freeboard.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("	<!-- partial:index.partial.html -->\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"at-section\">\n");
      out.write("			<div class=\"at-section__title\">The Team</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"at-grid\" data-column=\"3\">\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img\n");
      out.write("							src=\"https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Aaron Rossi</div>\n");
      out.write("					<div class=\"at-user__title\">CEO &amp; Co-Founder</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img src=\"https://s3.amazonaws.com/uifaces/faces/twitter/rem/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Marco Gomez</div>\n");
      out.write("					<div class=\"at-user__title\">Co-Founder, Creative Director</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img\n");
      out.write("							src=\"https://s3.amazonaws.com/uifaces/faces/twitter/boheme/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Brad Joe</div>\n");
      out.write("					<div class=\"at-user__title\">Office Manager</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img src=\"https://s3.amazonaws.com/uifaces/faces/twitter/ok/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Mitch Petty</div>\n");
      out.write("					<div class=\"at-user__title\">Lead Developer</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img src=\"https://s3.amazonaws.com/uifaces/faces/twitter/jsa/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Philip Satemburgo</div>\n");
      out.write("					<div class=\"at-user__title\">Community Manager</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img\n");
      out.write("							src=\"https://s3.amazonaws.com/uifaces/faces/twitter/marcogomes/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">George Petty</div>\n");
      out.write("					<div class=\"at-user__title\">Lead Designer</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img\n");
      out.write("							src=\"https://s3.amazonaws.com/uifaces/faces/twitter/dancounsell/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Petty Rossi</div>\n");
      out.write("					<div class=\"at-user__title\">Brand Designer</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img\n");
      out.write("							src=\"https://s3.amazonaws.com/uifaces/faces/twitter/kolage/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">Mitch Rossi</div>\n");
      out.write("					<div class=\"at-user__title\">New Business</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"at-column\">\n");
      out.write("				<div class=\"at-user\">\n");
      out.write("					<div class=\"at-user__avatar\">\n");
      out.write("						<img\n");
      out.write("							src=\"https://s3.amazonaws.com/uifaces/faces/twitter/tonychester/128.jpg\" />\n");
      out.write("					</div>\n");
      out.write("					<div class=\"at-user__name\">George Mitch</div>\n");
      out.write("					<div class=\"at-user__title\">UX Designer</div>\n");
      out.write("					<ul class=\"at-social\">\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("						<li class=\"at-social__item\"><a href=\"\"> <svg\n");
      out.write("									viewBox=\"0 0 24 24\" width=\"18\" height=\"18\"\n");
      out.write("									xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("                <path\n");
      out.write("										d=\"M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z\"\n");
      out.write("										fill-rule=\"evenodd\"></path>\n");
      out.write("              </svg></a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- partial -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
